FROM python:3.9-slim

COPY . .

RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y portaudio19-dev
RUN apt-get install -y protobuf-compiler

RUN pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I=proto --python_out=. --grpc_python_out=proto proto/mafia_service.proto

CMD python3 voice_chat/server_tcp.py & python3 rest/server.py
CMD cd rest && python -m flask run --host=0.0.0.0 --port=80
