name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for server
      run: docker build . -f Dockerfile-server
    - name: Build the Docker image for client
      run: docker build . -f Dockerfile-client
